$ANSIBLE_VAULT;1.1;AES256
35326163633362356331306535336133346235313034616165353333313938393338313738653066
3965613231333138663831303265363736663335613335310a616134356663643838343737616439
35396336626339393161363333336661313165326139316661336539626638643064613461623237
3464303930323737610a356466656366326235333730386130623666393535663538636462363931
35316161303939346664303032336165653134653865646239343031383936343536653163363639
32386266393366373333303262393936373365313332353734396666363536663538343931623833
64633131333266303635626633353331393163656638626239366163306562393666316266363365
32656536656235666362316539643133393063313762306238396361636463613262613331316465
36326530366363323064323233663762663565393833623030396637333965326338623966316430
37353730326132326238336563646263626535353661343766643862336235313230633961306532
63303232643730383466633032333035316561653061666631303764396261323136663130346636
63616631386161336539376337316336343133393530643532666130363762386233626231656534
61353861343838343062636464303662336132316632396234343966313935316430386363373730
63613962373039666132663739393232306365383236323631633065363832376336366665343464
31313835623063623566336138633166393635656165633161373433323938373137383066323062
32343932633033383334376438303839356537383861303139613138396166653661333465303637
33633335343635363831633762363135306666316131303830643266616132333165
